# require:
#   - rubocop-rspec

AllCops:
    SuggestExtensions: true
    NewCops: enable
    Exclude:
      - images/bounding_box.rb

Naming/VariableNumber:
  Exclude:
    - images/us_counter_sheet.rb